### ISSUE TITLE
Get attr_secure working on Jruby

### ISSUE THREAD

**Issue by neilmiddleton** [neilmiddleton/attr_secure#6]
AR's dependency is causing tests to fail:

```
An error occurred while installing yajl-ruby (1.1.0), and Bundler cannot continue.
```

**Comment by dmathieu** [comment]
Actually, the dependency to yajl-ruby is not on AR, it's on Fernet.
[The master gemspec](https://github.com/hgmnz/fernet/blob/master/fernet.gemspec) has no dependency to yajl-ruby. Updating to it should fix the problem.

**Comment by neilmiddleton** [comment]
Fernet's going through some changes at the moment so I'm going to hold off on this for now.  I've released the current version as 0.1.0.  When Fernet updates it'll go to 0.2.0 as the encryption methods will change slightly.

**Comment by dmathieu** [comment]
Master is now using the prerelease of fernet 2.0, which solves the yajl issue.
There's still an issue with the sqlite3 gem which can't be installed on jruby either though.

**Comment by neilmiddleton** [comment]
If we're using Fernet 2.0 then we need to provide a way to update stuff that's already existing in a system.  Fernet 2.0s encryption works differently now.

**Comment by dmathieu** [comment]
Would having an `OldFernet` module, allowing to encrypt and decrypt the older way (and therefore to build migration scripts) be ok with you?
